name: mne_bids
channels:
- defaults
- conda-forge
dependencies:
- python<3.9
- pip
- mkl
- numpy>=1.16.0
- scipy>=1.2.0
- pandas>=0.24.0
- scikit-learn>=0.21.0
- matplotlib<3.4
- pybv>=0.4.0
- pip:
  - mne_bids
  - mne>=0.23.0
  - nibabel>=2.5.0
  - nilearn
  - openneuro-py

